Repository pagopa/pagopa-payment-wallet-event-dispatcher-service, pull requests merged in 2024-10, with the labels that each got.

#33 chore: CHK-3328 add kafka to local develop
  docker-compose.yml
Labels: size/small, skip-release, ignore-for-release

#32 Feat [CHK-3330] Implementation of producer for EventHub
  README.md
  build.gradle.kts
  docker-compose.yml
  env.example
  gradle.lockfile
  gradle/verification-metadata.xml
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-prod.yaml
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/WalletEventDispatcherApplication.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/audit/LoggingEvent.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/WalletCDCClientConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/properties/RetrySendPolicyConfig.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/properties/WalletCDCConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/service/WalletCDCService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/service/WalletCDCServiceTest.kt
  src/test/resources/application.properties
Labels: size/large, minor, chart-minor

#35 fix(deploy-workflow): fix azure pipeline name
  .github/workflows/deploy.yml
Labels: patch, chart-patch, size/small

#31 chore(last usage): remove unused logic
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/api/WalletsApi.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/QueueConsumerConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletUsageQueueConsumer.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/service/WalletUsageService.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/api/WalletsApiTest.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletUsageQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/service/WalletUsageServiceTest.kt
Labels: size/small, minor, chart-minor

#36 Feat [CHK-3349] Join consumer and producer code
  README.md
  docker-compose.yml
  env.example
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-prod.yaml
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/audit/LoggingEvent.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/WalletCDCClientConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/properties/WalletCDCConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletCdcQueueConsumer.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/service/WalletCDCService.kt
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletCdcQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/service/WalletCDCServiceTest.kt
  src/test/resources/application.properties
Labels: size/small, minor, chart-minor

#37 Feat [CHK-3333] Added integration tests
  .devops/pay-wallet-code-review-pipelines.yml
  docker-compose.yml
  docker-local/example-event-result.json
  docker-local/example-event.json
  env.example
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/WalletCDCClientConfiguration.kt
  src/main/resources/application.properties
Labels: size/small, minor, chart-minor
