Repository pagopa/pagopa-payment-wallet-event-dispatcher-service, pull requests merged in 2024-04, with the labels that each got.

#2 refactor: remove unused folders
  .opex/env/prod/backend.ini
  .opex/env/prod/backend.tfvars
  .opex/env/prod/config.yaml
  .opex/env/prod/terraform.tfvars
  integration-test/README.md
  integration-test/run_integration_test.sh
  integration-test/src/README.md
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.prod
  integration-test/src/config/.env.uat
  integration-test/src/features/example.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/support/common.js
  integration-test/src/step_definitions/support/steps.js
  performance-test/README.md
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx.conf
  performance-test/run_performance_test.sh
  performance-test/src/README.md
  performance-test/src/local.environment.json
  performance-test/src/main_scanario.js
  performance-test/src/modules/client.js
  performance-test/src/test-types/constant.json
  performance-test/src/test-types/load.json
  performance-test/src/test-types/smoke.json
  performance-test/src/test-types/soak.json
  performance-test/src/test-types/spike.json
  performance-test/src/test-types/stress.json
  postman-collection/README.md
  postman-collection/run_newman.sh
Labels: size/large, patch, chart-patch

#4 feat: use config file for codeql instead of managed config
  .github/workflows/codeql.yml
Labels: patch, chart-patch, size/small

#8 fix: add CI/CD pipeline configuration
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  build.gradle.kts
  gradle/verification-metadata.xml
Labels: size/large, patch, chart-patch

#9 fix(deploy): add missing azure devops templates
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/gradle-github-release.yml
  .devops/azure-templates/helm-microservice-chart-deploy.yml
  build.gradle.kts
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/WalletEventDispatcherApplication.kt
Labels: patch, chart-patch

#5 [CHK-2708] Setup storage queue
  .gitignore
  azurite/Dockerfile
  azurite/create-queues.sh
  build.gradle.kts
  docker-compose.yml
  env.example
  gradle.lockfile
  gradle/verification-metadata.xml
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/WalletEventDispatcherApplication.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/common/queue/QueueEvent.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/common/queue/TracingInfo.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/common/serialization/WalletEventMixin.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/QueueConsumerConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/SerializationConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/domain/WalletEvent.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletUsageQueueConsumer.kt
  src/main/resources/application.properties
  src/main/resources/banner.txt
  src/main/resources/logback-spring.xml
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletUsageQueueConsumerTest.kt
  src/test/resources/logback-spring.xml
Labels: size/large, patch, chart-patch

#11 fix(gradle.lockfile): add javadoc and sources as trusted jars
  gradle/verification-metadata.xml
Labels: size/small, skip-release

#10 [CHK-2651] Add logic to update wallet usage
  .sdkmanrc
  build.gradle.kts
  env.example
  gradle.lockfile
  gradle/verification-metadata.xml
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/WalletEventDispatcherApplication.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/api/WalletsApi.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/WebClientConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/properties/WalletsApiConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/domain/WalletEvent.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/domain/WalletUpdateUsageError.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletUsageQueueConsumer.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/service/WalletUsageService.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/utils/Tracing.kt
  src/main/resources/application.properties
  src/main/resources/banner.txt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/WalletEventDispatcherApplicationTest.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/api/WalletsApiTest.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletUsageQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/service/WalletUsageServiceTest.kt
  src/test/resources/application.properties
Labels: size/large, patch, chart-patch

#12 fix: Wrong UAT keyvault name
  helm/values-uat.yaml
Labels: patch, chart-patch, size/small
