Repository pagopa/pagopa-payment-wallet-event-dispatcher-service, pull requests merged in 2024-06, with the labels that each got.

#14 feat(pay-wallet): CHK-2928 add helm value for pay-wallet
  .devops/pay-wallet-deploy-pipelines.yml
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
Labels: size/small, minor, chart-minor

#16 feat(values): CHK-2948 add affinity to select pay-wallet nodepool
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
Labels: patch, chart-patch, size/small

#17 Chk 2948 select nodepool
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
Labels: size/small

#18 feat(pipeline): CHK-2946 Add pipeline for prod
  .devops/pay-wallet-deploy-pipelines.yml
  helm/pay-wallet-values-prod.yaml
Labels: minor, chart-minor

#20 chore(helm-itn): align itn env
  helm/pay-wallet-values-prod.yaml
Labels: patch, chart-patch, size/small

#19 feat(wallet-expiration): add patch wallet status api call
  README.md
  build.gradle.kts
  gradle.lockfile
  gradle/verification-metadata.xml
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/api/WalletsApi.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/domain/WalletUpdateUsageError.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/exceptions/WalletPatchStatusError.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/exceptions/WalletUpdateUsageError.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/service/WalletUsageService.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/api/WalletsApiTest.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletExpirationQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletUsageQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/service/WalletUsageServiceTest.kt
Labels: size/large, minor, chart-minor

#21 fix(helm): remove space for queue name
  helm/pay-wallet-values-prod.yaml
  helm/pay-wallet-values-uat.yaml
Labels: chart-patch, size/small, ignore-for-release

#23 chore(weu to itn): comment out deploy and helm values
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/large, skip-release

#24 Set at least 3 replicas for PROD env
  helm/pay-wallet-values-prod.yaml
Labels: size/small, ignore-for-release, chart-minor

#25 fix(ingress): delete .prod in ingress endpoint
  helm/pay-wallet-values-prod.yaml
Labels: chart-patch, size/small, ignore-for-release

#26 feat: [CHK-2982] Added tracing for queue messages
  Dockerfile
  build.gradle.kts
  docker-compose.yml
  gradle.lockfile
  gradle/verification-metadata.xml
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/OtelConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletUsageQueueConsumer.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/queues/commons.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/utils/Tracing.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletExpirationQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletUsageQueueConsumerTest.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/utils/TracingMock.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/utils/TracingTest.kt
Labels: size/large, minor, chart-minor

#27 fix: [CHK-2982] Enabled spring integration otel
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-prod.yaml
  helm/pay-wallet-values-uat.yaml
Labels: chart-patch, size/small

#28 feat(helm): Enabled blue deployment for uat environment
  helm/pay-wallet-values-uat.yaml
Labels: size/small, ignore-for-release, chart-minor
