Repository pagopa/pagopa-payment-wallet-event-dispatcher-service, pull requests merged in 2025-01, with the labels that each got.

#45 fix: ingress value for uat env
  helm/pay-wallet-values-uat.yaml
Labels: patch, chart-patch, size/small

#46 fix(prod deployment): tune up prod deployment values
  helm/pay-wallet-values-prod.yaml
Labels: patch, chart-patch, size/small

#47 chore: increase gradle heap size
  gradle.properties
Labels: size/small, skip-release

#48 [PIDM-41] chore(azdo-pipeline-tasks): update tasks versions
  .devops/pay-wallet-code-review-pipelines.yml
Labels: size/small, skip-release, ignore-for-release

#49 feat: warmup function support for services
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/common/cdc/LoggingEvent.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/QueueConsumerConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletCdcQueueConsumer.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletExpirationQueueConsumer.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/service/WalletCDCService.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/warmup/ServicesWarmup.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/warmup/annotations/WarmupFunction.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/warmup/utils/EventsUtil.kt
  src/main/kotlin/it/pagopa/wallet/eventdispatcher/warmup/utils/WarmupRequests.kt
  src/test/kotlin/it/pagopa/wallet/eventdispatcher/warmup/utils/WarmupRequestsTest.kt
  src/test/resources/application.properties
Labels: size/large, minor, chart-minor
